### ISSUE TITLE
مثال های واقعی

### ISSUE THREAD

**Issue by abbasfisal** [3lf/design-patterns-for-humans#2]
لطفا دوستانی که تجربه استفاده از دیزاین پترن ها رو توی پروژه های واقعی دارند بنویسن (‌میتونن سناریویی که پیش اومده و رفتن سراغ یک دیزاین پترن رو بگن)

**Comment by 3lf** [comment]
حتما عباس جان
ممنون بابت پیشنهاد خوبت
سعی میکنم خودم هر موردی که یادم اومد رو اضافه بکنم و از دوستانم بخوام که اینکار رو بکنن

**Comment by 3lf** [comment]
به توضیحات readme هم پیشنهادت رو اضافه کردم.
